### ISSUE TITLE
Other filters?

### ISSUE THREAD

**Issue by tjasmin111** [Arslanex/Doctor_Strange_Filter#2]
Very interesting project, thank you. But can we do a filter to make nose smaller?

**Comment by Arslanex** [comment]
Of course, specially designed face and nose landmark models can be used for this purpose.

**Comment by tjasmin111** [comment]
Thanks. Using mediapipe we can get nose landmarks and mesh. But what to do with it to make it look smaller?

**Comment by Arslanex** [comment]
You will move and relocate this landmarks for it. It will not looked professiona but it's a start

**Comment by tjasmin111** [comment]
Well, it's not just to change the coordinates of landmakrs. It's moving the nose texture along with it. How to do that? Do you have any examples?

**Comment by Arslanex** [comment]
I haven't worked on this kind of project and so I don't have an example. Maybe I will do a project in the future, but now I have two different project ideas in my mind. I want to share them before the end of the month.
